### ISSUE TITLE
Improve response time

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/taar-api#14]
According to new relic the media response time is between 2 and 3 seconds, while the 95th percentile goes up to 5 seconds.
![capture](https://user-images.githubusercontent.com/508377/31773378-798865ca-b4da-11e7-885c-a83c57929190.JPG)
Once #13 is solved, we should be able to understand where we are spending all this time.

**Comment by crankycoder** [comment]
The switch from HBase to DynamoDB has dramatically cut our response times down to <73ms.

cc/ @mlopatka 

![transactions_-_taar_api__prod__-_new_relic](https://user-images.githubusercontent.com/4829/37160323-f06dbd2e-22bd-11e8-82a0-4ad2f62983ba.jpg)

**Comment by crankycoder** [comment]
FYI - the database lookups are down from ~400ms in HBase to ~20ms with Dynamo.

![taar_api_prod___datadog](https://user-images.githubusercontent.com/4829/37160542-77685f28-22be-11e8-984e-82eb3f4d84f8.jpg)
