### ISSUE TITLE
Refactor this to use Flask instead of Django

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/taar-api#21]
After discussing #20 with @jezdez , it seems that we might not make good use of Django for this project: all we're really doing is calling the TAAR api with some parameters coming from the URL.

We could refactor this, reducing the overall complexity, by making it a one-file flask application.

There are a few things to consider though:

- do we even need things as CSP, HSTS setup, etc.?
- would we need Django for some other feature here?

**Comment by crankycoder** [comment]
This was done ages ago.
